### ISSUE TITLE
wantFile plugin method works only with directory as path parameter

### ISSUE THREAD

**Issue by ykvch** [nose-devs/nose#1016]
**Steps:**
1. Create plugin with wantFile method and tests inside files matching test*.py pattern
2. Call nose runner with that plugin and test*.py as parameter

**Actual:**
2. Tests are run. Plugin method wantFile is not called

**Expected:**
2. wantFile called for every file matching test*.py

_Note:_ wantFile works if path parameter is a directory

**Comment by jszakmeister** [comment]
Two things: 1) I'm not sure this is a bug.  If you explicitly name a file, it seems reasonable to test it.  2) Nose is unmaintained these days.  You'd do better to look at [Nose2](/nose-devs/nose2).

**Comment by ykvch** [comment]
> > 1) I'm not sure this is a bug. If you explicitly name a file, it seems reasonable to test it

Yeah, thought about this too (and then actually saw that in the code). While it was a little surprising to see plugin "not working" (at a first glance) while trying to run a subset of my tests from directory by a wildcard.
Thanks.
