### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by vjayara1** [nose-devs/nose#1019]
Hello, I am hitting the following error when installing rosdep on a Yocto build,

|   File "/home/venkat/ros-build/krogoth/build/tmp/sysroots/x86_64-linux/usr/lib/python2.7/distutils/core.py", line 111, in setup
|     _setup_distribution = dist = klass(attrs)
|   File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 269, in __init__
|   File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs
|   File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 827, in resolve
|   File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 1072, in best_match
|   File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 1084, in obtain
|   File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 380, in fetch_build_egg
|   File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 634, in easy_install
| distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nose>=1.0')
| ERROR: python setup.py build execution failed.

Any way to fix or work around this ? I have tried different proxy settings, but of no use. I do see that python-nose package is fetched successfully, but fails in do_compile step of rosdep, which is strange. I see the package in my build directory.

**Comment by jszakmeister** [comment]
Sorry, but I don't know.  Also, the issue tracker is not for asking questions.  There are other better forums for that.  FWIW, this looks like a problem with your environment.
