### ISSUE TITLE
where is `coverage`'s own nose plugin?

### ISSUE THREAD

**Issue by johnyf** [nose-devs/nose#1022]
The documentation [mentions](https://github.com/nose-devs/nose/blob/b3a505071d6de526d470218d310019d04280b69c/doc/plugins/cover.rst) that "Newer versions of coverage contain their own nose plugin which is superior to the builtin plugin".

I cannot find this plugin within the code of `coverage.py`. Could you please note where it can be found?

**Comment by nedbat** [comment]
Coverage.py does not provide a nose plugin, and never has. At one time, we thought we might, but we did not.

**Comment by johnyf** [comment]
Thank you for the information. It is worth noting that the documentation file mentioned in the OP was last changed on Mar 4 2010, so, clearly, it is outdated. I've corrected the error in #1025.
