### ISSUE TITLE
When using verbose mode (-v), display test names in nosetest's input format for easy copy-paste

### ISSUE THREAD

**Issue by HaraldNordgren** [nose-devs/nose#1024]
So instead of

`testWriteDoesNotStripAnsi (colorama.tests.ansitowin32_test.AnsiToWin32Test) ... ok`

show something like

`colorama.tests.ansitowin32_test:AnsiToWin32Test.testWriteDoesNotStripAnsi ... ok`

The second form corresponds to the input format to `nosetests` when running single tests or classes.

**Comment by chaoflow** [comment]
I also like that in your pull request you kept the plain test method name at the front!

**Comment by HaraldNordgren** [comment]
The project us unmaintaned and the tests are failing on origin/master. Closing the issue.
