### ISSUE TITLE
nosetests error "TypeError (Cannot extend enumerations)"

### ISSUE THREAD

**Issue by abcondas** [nose-devs/nose#1056]
I've created a testsuite.py module that sets up a python testsuite.  This module imports an enum class with 3 members:
```
# test_helper.py
class TestType(Enum):
    ONE = 1
    TWO = 2 
    THREE = 3
```
```
# testsuite.py
...
from test_helper import TestType
... create, add, and run testsuite
```
when I execute this module using nosetests I receive the error:
Failure: TypeError (Cannot extend enumerations) ... ERROR

nose seems to be doing discovery and attempts to extend the enum class which is not allowed in python.  Seems like a bug.  Please advise.

**Comment by datalogics-robb** [comment]
Nose looks for classes whose names begin with ‘Test’ and considers those tests to be run.
Perhaps your example would work as you would expect, if it had a name that did not being with 'Test'

**Comment by abcondas** [comment]
Thank you, Rob!  That was it.  I should have figured that out...  (blush)
