### ISSUE TITLE
Is there any plan to port nose code to Python 3? 

### ISSUE THREAD

**Issue by opethe1st** [nose-devs/nose#1080]
I recently forked this repo to test something and noticed it still have print statements not functions. 
Any plans to port especially given support for Python 2 is coming to an end soon? 
I am volunteering to  help.

**Comment by Drachenfels** [comment]
Looking at number of pull requests and issues, we may assume that nose development has stopped about 2 years ago. Maybe it makes sense to fork this project and go from there?

**Comment by jszakmeister** [comment]
You should be looking at [Nose2](https://github.com/nose-devs/nose2) as the future of Nose.
