### ISSUE TITLE
Please release 1.3.8

### ISSUE THREAD

**Issue by MatthijsBurgh** [nose-devs/nose#1112]
My student team depends on 14cbbc3f6d282d9c48bb3d6aa8c048be124780ab. This is not in 1.3.7, so please release 1.3.8 to pip.

**Comment by MatthijsBurgh** [comment]
@jp @kumar303 @liucougar @pjenvey @thedrow could you please consider this?

**Comment by MatthijsBurgh** [comment]
@jp @kumar303 @liucougar @pjenvey @thedrow friendly ping ;)

**Comment by hugovk** [comment]
https://nose.readthedocs.io/en/latest/ says:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

And after six years, it's very unlikely there'll be a new release.

In the short term, you can install directly from Git:

* https://stackoverflow.com/a/13754517/724176

But in the longer term I'd strongly suggest moving away from nose, especially as it will stop working in Python 3.10 (the below issue says 3.9 alpha, but 3.10 is the actual first release where nose is broken):

* https://github.com/nose-devs/nose/issues/1099

I recommend pytest:

* https://pytest.org/

**Comment by MatthijsBurgh** [comment]
I don't expect a new release. 1.3.8 is already marked as an release on GitHub. So it would be convenient if that was also released on pip.
