### ISSUE TITLE
multiprocess functionality does not play way with generators

### ISSUE THREAD

**Issue by jpellerin** [nose-devs/nose#125]
<b>What steps will reproduce the problem?</b>

1.create a simple test generator function like:

def test_foo():
    for i in range(10):
        yield foosleep, i

def foosleep(n):
    time.sleep(4)

<b>What is the expected output? What do you see instead?</b>

Using --processes=10, all tests should complete in ~4s.
Instead, it takes 40s since the next test does not start until the last is finished.

<b>What version of the product are you using? On what operating system?</b>

1.0.0 on ubuntu 10.04 x86-64

<b>Please provide any additional information below.</b>

i'm guessing we need a way to collect all tests before they are sent to the parallelizer?

Google Code Info:
Issue #: 399
Author: ffxvzero@gmail.com
Created On: 2011-02-19T09:04:15.000Z
Closed On: 2011-05-02T19:59:00.000Z

**Comment by benmosher** [comment]
I am also seeing my generated tests run sequentially, under Python 2.7 + nose 1.3.7.
