### ISSUE TITLE
Package Level setUp Doesn't Run

### ISSUE THREAD

**Issue by jpellerin** [nose-devs/nose#286]
<b>What steps will reproduce the problem?</b>
1. Please see attached unit tests. if package **init**.py contains
"setup()" the function is run appropriately. If the function is named
"setUp()" it isn't run. The same is true for "tearDown()"

<b>What is the expected output? What do you see instead?</b>
setUp() and tearDown() functions defined at the package level run.

<b>What version of the product are you using? On what operating system?</b>
0.10.4 on Ubuntu Hardy

<b>Please provide any additional information below.</b>
The patch is in suite.py changing to:
    moduleSetup = ('setup_module', 'setupModule', 'setUpModule', 'setup',
'setUp')
    moduleTeardown = ('teardown_module', 'teardownModule', 'tearDownModule',
                      'teardown', 'tearDown')

Google Code Info:
Issue #: 211
Author: AgilityN...@gmail.com
Created On: 2008-10-16T18:30:29.000Z
Closed On: 2009-04-19T15:55:40.000Z

**Comment by sinchb** [comment]
+1

my nosetest doesn't recognize package setup and teardown
