### ISSUE TITLE
Where is version 1.1.3 ?

### ISSUE THREAD

**Issue by Djabx** [nose-devs/nose#494]
When we read the documentation ( http://readthedocs.org/docs/nose/en/latest/index.html ) the lastest version is 1.1.3, but on on PyPy ( http://pypi.python.org/pypi/nose/ ) the latest is 1.1.2 (and with easy_install).

Where can I download 1.1.3 ?

**Comment by jayvdb** [comment]
It looks like 1.1.3 never happened according to github releases and pypi releases, and 1.2 was the next release.

This can be closed now?
