### ISSUE TITLE
Error with module named "setup"

### ISSUE THREAD

**Issue by jpellerin** [nose-devs/nose#54]
<b>What steps will reproduce the problem?</b>
1. Create a package
2. Create a module within that package called "setup.py"
3. Run nose on that package

<b>What is the expected output? What do you see instead?</b>

Nose should ignore the module setup.  Instead, I get the following:

Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/nose/suite.py", line 183, in run
    self.setUp()
  File "/Library/Python/2.6/site-packages/nose/suite.py", line 264, in setUp
    self.setupContext(ancestor)
  File "/Library/Python/2.6/site-packages/nose/suite.py", line 287, in setupContext
    try_run(context, names)
  File "/Library/Python/2.6/site-packages/nose/util.py", line 482, in try_run
    (name, obj))
TypeError: Attribute setup of <module 'envbuilder' from 
'/Users/jason/src/envbuilder/envbuilder/__init__.pyc'> is not a python function. Only functions 
or callables may be used as fixtures.

<b>What version of the product are you using? On what operating system?</b>

0.11.1

Google Code Info:
Issue #: 320
Author: amnorv...@gmail.com
Created On: 2010-02-12T14:47:10.000Z
Closed On: 2011-11-25T05:35:44.000Z

**Comment by asmodehn** [comment]
I looks like I recently hit that bug on nose 1.3.1 and on 1.3.7:
I am using a install of nose in a custom location so please disregard that 'not in a venv' path. nose is working fine otherwise...

```
$ python -m nose --version
python -m nose version 1.3.7
$ python -m nose /abs_path_to/pyros-setup/pyros_setup/tests/test_rostest_nose.py --logging-level=DEBUG
E
======================================================================
ERROR: test suite for <module 'pyros_setup.tests.test_rostest_nose' from '/home/alexv/ROS/pyros-setup/pyros_setup/tests/test_rostest_nose.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/abs_path_to/devel/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/abs_path_to/devel/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/abs_path_to/devel/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/abs_path_to/devel/lib/python2.7/site-packages/nose/util.py", line 466, in try_run
    (name, obj))
TypeError: Attribute setup of <module 'pyros_setup' from '/abs_path_to/pyros-setup/pyros_setup/__init__.pyc'> is not a python function. Only functions or callables may be used as fixtures.
```

My `__init__.py` looks like this :

```
# -*- coding: utf-8 -*-
from __future__ import absolute_import

import logging
import os
import pkgutil
import types

import sys

from .setup import _PyrosSetup

[... more stuff here...]
```

and there is a `setup.py` module in the package, that contains a class `_PyrosSetup`.

I am including that package from my test like this : 

```
#!/usr/bin/env python
from __future__ import absolute_import

# Adding current package repository in order to be able to import it (if started with python cli)
import sys
import os
current_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.insert(1, current_path)  # sys.path[0] is always current path as per python spec
import time

# importing current package
import pyros_setup

[... more test stuff here...]
```

although working around it is simple enough (renaming setup.py) , such a behavior is quite surprising...
