### ISSUE TITLE
Look for unittest2 in skip plugin - commit

### ISSUE THREAD

**Issue by mjura** [nose-devs/nose#806]
Hi,

I don't know if it is proper place to posted about this, but I discovered problem with python-nose in versions 1.3.1 and above. I'm using it for testing python-kombu in version 3.0.15 and with python2.6 and unittest in version 0.5.1. After update python-nose from 1.3.0 to 1.3.3. SkipTest stopped working in my dev.
I have found that it is caused by this patch:
https://github.com/nose-devs/nose/commit/395a1bff9919f083eba9eb45800692e8ab55728c

Behavior is that SkipTest class is not loading any more.

Please let me know where can I post this problem.

**Comment by risicle** [comment]
I wonder if this might be a kombu issue as I'm also having the same problem running the tests for kombu 3.0.24 under python 2.6.

**Comment by risicle** [comment]
...and a very similar issue running the tests for celery 3.1.17 (by the same author) for python 2.6.

**Comment by jszakmeister** [comment]
Would be possible for you to print `type(self.result)` before that `addSkip()` call?  I'm curious which definition of `_TextTestResult` is being used.  Perhaps we need to try and import from unittest2 first, and then fallback to unittest.

**Comment by risicle** [comment]
`<class 'unittest._TextTestResult'>`

**Comment by jszakmeister** [comment]
Can you try this patch?

```diff
diff --git a/nose/result.py b/nose/result.py
index f974a14..1238d76 100644
--- a/nose/result.py
+++ b/nose/result.py
@@ -11,7 +11,7 @@ reporting.
 import logging
 try:
     # 2.7+
-    from unittest.runner import _TextTestResult
+    from unittest.runner import TextTestResult as _TextTestResult
 except ImportError:
     from unittest import _TextTestResult
 from nose.config import Config
```

It seems like that line is always importing with the wrong name, so it never works correctly. :-(

**Comment by jszakmeister** [comment]
Can you try this patch?

```diff
diff --git a/nose/result.py b/nose/result.py
index f974a14..1238d76 100644
--- a/nose/result.py
+++ b/nose/result.py
@@ -11,7 +11,7 @@ reporting.
 import logging
 try:
     # 2.7+
-    from unittest.runner import _TextTestResult
+    from unittest.runner import TextTestResult as _TextTestResult
 except ImportError:
     from unittest import _TextTestResult
 from nose.config import Config
```

It seems like that line is always importing with the wrong name, so it never works correctly. :-(

**Comment by jszakmeister** [comment]
@risicle ping

**Comment by risicle** [comment]
Nope still no luck, same error. (this is nose 1.3.4 I'm applying the patch to)

**Comment by jszakmeister** [comment]
Can you create a small test case that causes this issue?

**Comment by risicle** [comment]
Not really, it's not my code (not even a nose user)

**Comment by jszakmeister** [comment]
Unfortunately, I don't think I can be of any further help then. :-(

**Comment by risicle** [comment]
I was just packaging kombu for nixpkgs, so all I've done is disable its tests for python 2.6.
