### ISSUE TITLE
python segfault while runnning with xunit support enabled

### ISSUE THREAD

**Issue by mojaves** [nose-devs/nose#817]
Hi, oVirt/VDSM developer here. oVirt is an open-source virtualization platform (http://www.ovirt.org/Home), and one of our core components, VDSM, is a system daemon written in python; we use nose to test it.

If I run our VDSM testsuite with XUNIT output enabled, I get a segfault from cpython (python 2.7.5) It does happen quite frequently, even though not every time.

Please note that if we run our test collection one test at time (instead of in just one big pass), everything seems to work nicely.

Instruction to reproduce:
$ git clone http://gerrit.ovirt.org/p/vdsm.git
$ cd vsm
$ ./configure && make
$ export NOSE_WITH_XUNIT=1
$ export NOSE_SKIP_STRESS_TESTS=1
$ make check
(wait some seconds and see it segfault)

reproduced on python 2.7.5 with nose 1.3.0, 1.3.1, 1.3.2 and from git (71b5ee2161289f56318308f070fb9e91fa6017b1)

**Comment by wat-izz** [comment]
@mojaves Did you find a workaround for this in the end?
