### ISSUE TITLE
Upload wheels to pypi

### ISSUE THREAD

**Issue by aragilar** [nose-devs/nose#869]
Currently nose lacks wheels on pypi, can you upload them?

**Comment by jszakmeister** [comment]
I've not tried wheels before.  Is it painful?  Why do you need them given that nose is pure Python?

**Comment by aragilar** [comment]
>
> That doesn't seem like a big win to me, given that it only takes a few
> seconds as-is.
>
I timed how long `pip install nose` took in a clean python3 virtualenv, it
takes 6 seconds to install the sdist vs 0.7 seconds for a wheel (this
excludes download time, as I've got a cache). This isn't too bad, but if
you are installing multiple packages, then it's quite noticeable (hence I
keep a wheel cache using devpi).

> But, I'm sure there's something more than just the invocation. I assume
> you have to install the wheel package?
>
Yes, you need setuptools and wheel.

> What configuration does it need?
>
Since nose uses 2to3, then it doesn't need any

> Will the typical invocation do the right thing?
>
`python setup.py bdist_wheel` creates a wheel compatible to whatever
version of python `python` is
`python setup.py upload bdist_wheel` creates and uploads a wheel
`python setup.py upload bdist_wheel -s` creates, uploads and signs a wheel
This is the same as an sdist, except that as nose uses 2to3, you need to
create two wheels, one for python 2, and one for python 3. So you'd need to
call the setup.py with a python 2 interpreter and a python 3 interpreter.

> Do you have to run wheel under two different interpreters to get the right
> results? What are the commands that should be invoked?
>
See above

> Do I need to sign the wheels?
>
In as much as you need to sign sdists (you can, but don't need to).

> Sorry for all the questions, but it seems like there should be a little
> more thought about it than just calling bdist_wheel, and the current
> documentation seems a bit lacking on what the best practices should be. :-(
>
Yeah,
https://packaging.python.org/en/latest/distributing.html#packaging-your-project
skips what to do if you're using 2to3...

**Comment by jszakmeister** [comment]
[snipped]
Thanks for the answers.

> `python setup.py upload bdist_wheel` creates and uploads a wheel
> `python setup.py upload bdist_wheel -s` creates, uploads and signs a wheel

I'm assuming that should really be `python setup.py bdist_wheel upload` (order of bdist_wheel and upload swapped).  I'll give it a whirl though.

**Comment by jszakmeister** [comment]
Okay, wheels have been uploaded, and they appear to work.  Thanks for the help!
