### ISSUE TITLE
nose 'lock up' silently under jenkins

### ISSUE THREAD

**Issue by Martin-Spamer** [nose-devs/nose#870]
Given a python 2.7 test suite being run through nose that uses selenium + phantomjs.
When the selenium + phantomjs throws an exceptions, e.g. (WebDriverException or NoSuchElement )
Then the nose job under jenkins hangs up and will not proceed to the end.
And there is nothing show in the logs files 

Surely the expected behaviour for Exceptions should be the same as an Assertion with nose capturing the exception and reporting this as a test failure and not simply failing silently.

 --- edited for grammar & clarity ---

**Comment by jszakmeister** [comment]
> Surely the expected behaviour should be the same as an Assertion with nose capturing the exception and reporting this as a test failure and not simply failing silently.

What makes you think that this is a Nose bug?  AFAIK, we're not doing anything special in that environment.  I suspect there's something else at play rather than Nose failing to act properly.

**Comment by Martin-Spamer** [comment]
I think this is nose because.  If I wrap the test with try/except, the last thing I see in the jenkins log is the printed exception.

    def test_something(self):
        try:
            logging.info(self)
            assert self.given_some_page()
        except Exception as exception:
            print exception
            self.fail(exception)

    def test_page_valid_with_raise(self):
        try:
            logging.info(self)
            assert self.given_some_page()
        except Exception as exception:
            print exception
            raise exception

The reason I think this is locked up is the jenkins log is frozen, as per the attached image.

![jenkins-log](https://cloud.githubusercontent.com/assets/2852862/5666769/f3d9a876-9759-11e4-8616-ee402edf0ab8.png)

**Comment by jszakmeister** [comment]
Okay, this means it's likely getting stuck in Nose, but still doesn't point to Nose as the problem.  It could be your test environment or the plugins that you are using.

Nose isn't doing anything special here.  If it sees an error, it will mark it as such and continue on to the next test.  I'd suggest debugging things a little more and try to find out where things are failing.  You can pass some debug flags to nosetests to get some more information about what nose is doing using the `--debug` flag.  For instance, you could try `--debug=nose,nose.result` to see more about the runner and result.

I suspect something else in your setup is hanging things, though I'm not sure why.  Are you able to at least reproduce it locally that you can debug it more?  Or log into your Jenkins box to test there?  The Python debugger (pdb) might be your friend here too, if you can.

**Comment by Martin-Spamer** [comment]
I've tried this and it makes no difference to the lock up or doesn't provide any additional logging inform.

**Comment by jszakmeister** [comment]
> I've stopped use nose because it is not reliable but just tried this and it makes no difference to the lock up or doesn't provide any additional logging inform.

I don't see how it wouldn't provide more logging.  It certainly does for me.  Sorry to hear you've stopped using Nose, but I'm still not convinced your problem is in Nose.  What are you using now instead?

All I can say is Nose doesn't have any special behavior here: `AssertionError`s turn into failures, and any other `Exception` converts to an error.  But seeing as you're not using Nose any longer, I'm closing this.

**Comment by Martin-Spamer** [comment]
I've been running the tests with just python.

Where should this information appear?  The system console?

**Comment by Martin-Spamer** [comment]
Adding "--debug-log=nose.log" has produced some output and the job no longer hangs. e.g.

> nosetests --debug-log=nose.log --debug=nose,nose.result --with-xunit test/acceptance/test_*.py

This would seem to confirm the default logging is somehow becoming deadlocked.

**Comment by jszakmeister** [comment]
> This seems like it could be a clue into the problem, something must be deadlocked somewhere and the lack of output hints towards the sysout/syserr. Does nose use buffers or raw writing, what does it do if the buffered fill? IMHO a hard stop (SIGKILL/9) would be better than deadlock.

Logging is done through the logging package--we're not really doing anything special there, other than setting up some handlers.  Nose does capture the output through a "teeing" mechanism.  You can try using `--nocapture` to turn off the stdout capturing, and/or `--nologcapture` to turn of log capturing.  Does that help?
