### ISSUE TITLE
Cannot execute "nosetests" from the shell

### ISSUE THREAD

**Issue by roshammar** [nose-devs/nose#871]
I have a fresh install of OS X Yosemite. I have installed Python with Homebrew and then Nose with pip from Homebrew.

From ipython, I can import Nose and I can find Nose in /usr/local/lib/python2.7/site-packages/ so it seems to have installed fine.

However, I cannot run 'nosetests' from bash, the command is not found. On a Linux system I am using this works. Thinking it was a path issue, I searched for nosetests, but there is no such file anywhere on the system. Is this the expected behaviour? If not, would this be a Nose issue or a Homebrew issue?

**Comment by jszakmeister** [comment]
This is not a Nose issue, but an installation or Homebrew one.  That's really odd though.  I would have expected it to land in /usr/local/bin because Homebrew sets up a distutils.cfg that sets /usr/local as the prefix.  Perhaps your shell config is set up that it doesn't re-hash?  IIRC, `hash -r` will refresh it in bash.  But I'd do an `ls /usr/local/bin` and see if it's there.  If not, then I suspect the installation of Nose failed in some way.

**Comment by roshammar** [comment]
Thank you for looking into this. I have investigated this further and now understand what happened:

I installed several packages with pip from a dotfiles script. Nose was one of those packages. The installation of Nose failed near the end. The necessary Python files were installed, but it failed when installing its *man* files to /usr/local/man, since my user did not have the necessary permissions to write to /usr/local/man. The installation of the nosetests bin file was probably next up, but never executed.

Since I installed a long list of packages, and since I could import nose and since *pip list* actually listed nose as installed, I didn't realise it hadn't installed correctly.

Re-installing it with *sudo pip* fixed it.

I was, however, under the impression, that when using Homebrew, sudo shouldn't be necessary. Perhaps I should notify a Homebrew maintainer of the fact that *man* is the only directory in /usr/local that is owned by root rather than my user, and thus that some installations may fail due to this.

**Comment by jszakmeister** [comment]
> Perhaps I should notify a Homebrew maintainer of the fact that man is the only directory in /usr/local that is owned by root rather than my user, and thus that some installations may fail due to this.

Hmmm.  I thought Homebrew encouraged you to change the ownership of /usr/local.  So perhaps something else happened along the way to create that directory with the wrong permissions.  So I don't think it's necessarily a Homebrew problem either--just an unfortunate circumstance. :-)
