### ISSUE TITLE
setuptools nosetests command doesn't work within conda environment

### ISSUE THREAD

**Issue by anderspitman** [nose-devs/nose#873]
From within a conda environment, running the following command:

``python setup.py nosetests``

Gives this error:

``error: invalid command 'nosetests'``

Using my system python it seems to recognize the command, but I've been unable to get it to work within a conda environment. Nose is installed and I can run ``nosetests`` directly just fine, but setuptools integration isn't working.

**Comment by jszakmeister** [comment]
Is this a Nose problem or a conda one?  It seems like the latter to me as Nose works just fine outside that environment.  What makes you think this is a Nose problem?

My apologies, but I don't really like to install random projects onto my machine--I find that it's often more complicated that folks admit to, and it does things to my machine that I don't want.

With that said, what are you hoping for with this bug report?  Are you willing to look into the problem yourself and propose a patch?  Are you hoping I'm going to install conda and debug the problem?  I don't know what direction to take this. :-(

**Comment by anderspitman** [comment]
Hey @jszakmeister, not expecting you to just fix this out of hand, so no worries. I suspect the problem may be somewhere in nose, since people have had [similar issues with virtualenv](http://stackoverflow.com/questions/14969173/why-do-i-get-the-error-invalid-command-nosetests-when-i-run-nosetests-from-my), but it certainly may be some similarity between virtualenv and conda. I would be happy to help work on this, but I was hoping some of the nose people might have an idea what in the underlying architecture could possible cause this issue. Sounds like you're not aware of anything. I'll keeping poking around. Obviously feel free to close this if you're confident nose isn't the problem.

**Comment by jszakmeister** [comment]
I'm not sure why other people have faced similar problems.  All I can say is that I use this integration and it works under virtualenv.  It could be some other thing getting in the way, but I've not had any issues with it. :-(

And yes, you are correct, I'm not sure what Nose would be doing that's causing that problem.  Most of it is pretty standard distutils stuff.

**Comment by anderspitman** [comment]
I tried using virtualenv and it works for me as well. No idea whats going on with conda, but I'll let you know if I find anything that might be useful.

**Comment by jszakmeister** [comment]
> No idea whats going on with conda, but I'll let you know if I find anything that might be useful.

Thanks!  I hope you find the issue.

**Comment by mforbes** [comment]
Could someone explain a bit how setup should know that a command ``nosetests`` should exist?  It is really not obvious how nose teaches setuptools about the ``nosetests`` command, and hence it is difficult to figure out how conda might be causing this to fail.

**Comment by mforbes** [comment]
Another solution is to replace the conda version of nose with the pip install:

```bash
conda remove nose
pip install nose
```

Somehow the conda install is not properly the [entry point in ``setup.py``](https://github.com/nose-devs/nose/blob/master/setup.py#L35):

```python
...
        entry_points = {
        ...
        'distutils.commands': [
            ' nosetests = nose.commands:nosetests',
            ],
...
```

Not yet sure why.

**Comment by mforbes** [comment]
I am not sure exactly what the issue is, but somehow the presence and contents of the file: ``lib/python2.7/site-packages/nose-1.3.4-py2.7.egg-info`` from the conda package breaks things.  Removing this file and including instead the ``lib/python2.7/site-packages/nose-1.3.4.dist-info`` installed by ``pip`` fixes the problem.  I will submit a bug report to the conda maintainers if I can figure out where such a report should be submitted.

**Comment by jtojnar** [comment]
We have the same issue in Nixpkgs and I decided to work around it by [creating the `entry_points.txt` manually](https://github.com/NixOS/nixpkgs/pull/332225).
