### ISSUE TITLE
No module named pylons.test but this isn't a pylons app?

### ISSUE THREAD

**Issue by Trii** [nose-devs/nose#874]
I am receiving the following error when running the command:
`nosetests --logging-level=ERROR --with-gae --no-path-adjustment --gae-application=/path/to/my/app`

```
nose-1.3.4-py2.7.egg/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin pylons = pylons.test:PylonsPlugin: No module named pylons.test
```

I am not sure why it is trying to load that plugin since I am not specifying it, nor do I have a `.noserc` or `nose.cfg` defined.

Any other pointers where I can look to find this error?

**Comment by jszakmeister** [comment]
What about in a setup.cfg?

**Comment by Trii** [comment]
I don't have one of those either. There are a few inside my google appengine sdk but none of them have anything referencing nose, pylons, etc.

I did just notice that fixture has an entry point listed

`./eggs/fixture-1.5.1-py2.7.egg/EGG-INFO/entry_points.txt:pylons = pylons.test:PylonsPlugin`
I wonder if that is causing it...

**Comment by jszakmeister** [comment]
Yes, that could very well be doing it.

**Comment by Trii** [comment]
Looks like they had an update recently so I'll check with them. Thanks for the second set of eyes!!
