### ISSUE TITLE
Nose doesn't collect tests when subpackage is given as argument

### ISSUE THREAD

**Issue by birkenfeld** [nose-devs/nose#875]
Given a directory structure like this:
```
.
└── test
    ├── __init__.py
    └── test_sub
        ├── __init__.py
        └── test_mod.py
```
and a single `test_func` function in the `test_mod.py` I get this behavior:
```
gbr@georg ~/nosebugtest> nosetests -v test
test.test_sub.test_mod.test_func ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
gbr@georg ~/nosebugtest> nosetests -v test.test_sub

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
gbr@georg ~/nosebugtest> nosetests -v test.test_sub.test_mod
test.test_sub.test_mod.test_func ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
gbr@georg ~/nosebugtest> nosetests -v test/test_sub         
test.test_sub.test_mod.test_func ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

I.e., when I want to run all tests in `test_sub`, I have to refer to it using `test/test_sub`, not `test.test_sub` to find the tests.

**Comment by birkenfeld** [comment]
With `--traverse-namespace` it works, which leads me to assume that the fault lies somewhere here:
https://github.com/nose-devs/nose/blob/master/nose/loader.py#L343

**Comment by jszakmeister** [comment]
Thanks for the nice bug report.  I have fixed this on master.  The problem was we were treating `foo.bar` the same as `foo/bar/__init__.py`, which is wrong.  I've added a couple of tests to help prevent a regression too.  I think this fix is worth getting out to the masses, so I'll look to cut a 1.3.5 sometime this week (if not later today).

**Comment by birkenfeld** [comment]
Great, thanks!
