### ISSUE TITLE
Nosetests opening too many files

### ISSUE THREAD

**Issue by miketwo** [nose-devs/nose#884]
While running nosetests I get a `too many open files` error.

This error is shared by others. See here: https://github.com/ga4gh/server/issues/131

I took an strace and graphed the file numbers as they show up in read(###,...) calls. Stack trace is here: https://gist.github.com/miketwo/d13bed512ed680913f02#file-nose_output-txt
![image](https://cloud.githubusercontent.com/assets/1082033/6518051/773e8ff6-c356-11e4-86e8-aef5e694f083.png)

I have confirmed this problem on versions 1.3.1 and 1.3.4, but the stack trace above is for 1.3.1.

Hope this helps.

**Comment by miketwo** [comment]
(Digging deeper and realizing this might be a problem on our end, and not with nose...)

**Comment by miketwo** [comment]
Yep, nevermind.  Nothing to see here.

**Comment by jszakmeister** [comment]
@miketwo Glad you found the issue!
