### ISSUE TITLE
Running individual test fails to run class setup/teardown

### ISSUE THREAD

**Issue by BenjamenMeyer** [nose-devs/nose#885]
I have a project that is laid out as follow:
```
module
   + tests
        + __init__.py
        + my_unit_test.py
        ...
        + my_last_unit_test.py
```

In module/tests/__init__.py I have some subclasses derived from unittest.TestCase to provide a common framework for all my various tests:

```python
import unittest

class MyBaseClass(unittest.TestCase):
     def setUp(self):
         super(MyBaseClass, self).setUp()

     def tearDown(self):
          super(MyBaseClass, self).tearDown()
```

For instance, a Controller test would have a MyControllerBaseClass derivative that would provide some functionality specific to controllers.

The tests themselves are also classes:

```python
from module.tests import MyBaseClass

class MyLocalTests(MyBaseClass):
     def setUp(self):
         super(MyLocalTests, self).setUp()

     def tearDown(self):
          super(MyLocalTests, self).tearDown()

    def mytest1(self):
           ...
```

The problem I am having is that when running under Python 2.7 I am trying to run a specific test as follows:

```
$ nosetests --cover-html --cover-branches module.tests.my_unit_test:MyLocalTests.mytest1
```

Neither the setUp nor the tearDown methods get run. I added output (via python's log) in each but it does not show up; the test is presently failing and I'm trying to debug it. I have enough tests that it would be very useful to run a specific test to be able to solve the problem; however unless setup and teardown are run, I am unable to do so.

Note: setup and teardown are run if I run all my tests as follows:

```
$ nosetests --cover-html --cover-branches module.tests
```

Trying to run a sub-set of tests from that also fails in the same way, e.g

```
$ nosetests --cover-html --cover-branches module.tests.my_unit_test:MyLocalTests
$ nosetests --cover-html --cover-branches module.tests.my_unit_test
```

**Comment by BenjamenMeyer** [comment]
Forgot to mention this is on Ubuntu 14.04 with nosetests version 1.3.4 and Python 2.7.6.

**Comment by jszakmeister** [comment]
I suspect that the setup and teardown aren't being picked up because no tests are being picked up.  Try renaming `mytest1` to `my_test`.

**Comment by BenjamenMeyer** [comment]
@jszakmeister the above was an example, the actual test in the ```format: test_name```

Here's the line:
````
$ nosetests --cover-html --cover-branches deuterium.tests.test_signature:TestSignature.test_basic
```

**Comment by jszakmeister** [comment]
@BenjamenMeyer I tried your example before posting my answer. :-)  It worked fine if I fixed the name.

**Comment by BenjamenMeyer** [comment]
I'll try to build a better example that I can provide as a gist.

The current repo I'm working in where I have the issue is not a public one. I usually call my tests 'test_descriptive_name' as opposed to 'mytest1' placeholder I used in the example above.

**Comment by BenjamenMeyer** [comment]
I've been trying to replicate it using an example project; however, I have been unable to. If I can find the detail that is causing and trace it back to nose I'll re-open. But for now, I'm going to close this.
