### ISSUE TITLE
Py 2 vs 3: test name discrepancy

### ISSUE THREAD

**Issue by montefra** [nose-devs/nose#887]
I've a test file `test_file.py`
```python
def test_func():
    "this is a test function"
    assert True

class TestClass(object):
    "this is a test class"
    @classmethod
    def setup_class(cls):
         cls.a = 'a'
    def test_method(self):
         "this is a test method"
          assert True
``` 

When I run `python2 setup.py nosetests` I get for both the docstring:
```
[...]
this is a test function ... ok
this is a test method ... ok
[...]
```
but  I run `python3 setup.py nosetests` I get the docstring only for the function:
```
[...]
this is a test function ... ok
test_file.TestClass.test_method ... ok
[...]
```
I don't know if it's a bug, but for sure it's not a feature

I'm using:
nose: 1.3.4
python 3.4.2
python 2.7.8

**Comment by jszakmeister** [comment]
This does seem like a bug.  Care to make a patch for it?

**Comment by montefra** [comment]
@jszakmeister have no idea where to start. If you can point me to the relevant parts, I can see if I can do something about it?

**Comment by jszakmeister** [comment]
I would start by getting some extra information about what is going on using: `nosetests --debug=nose.loader,nose.selector path/to/test_file.py`

Most of the setup is happening is nose.loader, IIRC.  That's where I'd expect the issue to be.  That should get you going in the right direction, I think.

**Comment by montefra** [comment]
@jszakmeister thank you. I'll investigate in the next days. I'll let you know if I have troubles.

**Comment by montefra** [comment]
I think I've found where the problem is: [`case.TestBase.shortDescription`](https://github.com/nose-devs/nose/blob/master/nose/case.py#L203). For some reason, the method `test_method` doesn't have a `__doc__` attribute.

This is what `python3 -m pdb `which nosetests` test_file.py` tells me:

```python
(Pdb) n
> nose/build/lib/nose/case.py(203)shortDescription()
-> func, arg = self._descriptors()
[...]
(Pdb) n
> nose/build/lib/nose/case.py(204)shortDescription()
-> doc = getattr(func, '__doc__', None)
(Pdb) p func
<unbound method TestClass.test_method>
(Pdb) getattr(func, '__doc__', None)
(Pdb) getattr(func, '__doc__')
[...]
(Pdb) n
> nose/build/lib/nose/case.py(203)shortDescription()
-> func, arg = self._descriptors()
(Pdb) 
> nose/build/lib/nose/case.py(204)shortDescription()
-> doc = getattr(func, '__doc__', None)
(Pdb) p func
<function test_func at 0x7ffcf77489e0>
(Pdb) p getattr(func, '__doc__')
'this is a test function'
```

This is what `python2 -m pdb `which nosetests` test_file.py` tells me:

```python
> nose/nose/case.py(202)shortDescription()
-> func, arg = self._descriptors()
(Pdb) 
> nose/nose/case.py(203)shortDescription()
-> doc = getattr(func, '__doc__', None)
(Pdb) p func
<unbound method TestClass.test_method>
(Pdb) p getattr(func, '__doc__')
'this is a test method'
[...]
> nose/nose/case.py(200)shortDescription()
-> if hasattr(self.test, 'description'):
(Pdb) n
> nose/nose/case.py(202)shortDescription()
-> func, arg = self._descriptors()
(Pdb) 
> nose/nose/case.py(203)shortDescription()
-> doc = getattr(func, '__doc__', None)
(Pdb) p func
<function test_func at 0x104e5f0>
(Pdb) p getattr(func, '__doc__')
'this is a test function'
```

I've tried to load `test_file.py` into `ipython3` and the docstring exists:

```python
In [4]: test = TestClass()
In [5]: test.test_method.__doc__
Out[5]: 'this is a test method'
```

Any idea of what's going on?
My guess is that it has something to do with `2to3`. The only difference that I see between the python2 and python3 cases is the for the former, the code comes from nose/nose (so the original source), while in the latter the code comes from nose/build/lib/nose (so the code processed by `2to3`)

----
Tested on python 2.7.6 and python 3.3.5 using fresh virtual environments. `nose` installed from master with `pip install -e /path/to/nose`

If you want I have a machine with python 3.4.x

**Comment by jszakmeister** [comment]
> I think I've found where the problem is: case.TestBase.shortDescription.

That's only the symptom. :-)  The problem is elsewhere.  In Python 3 we wrap some methods, and it's there that we run into the problem.  See ae14c6ec9327465087a19bc3006a26acc690d3da for the details.

Thanks for looking into the problem!

**Comment by montefra** [comment]
Thanks for fixing it. Now it works from python 3:

```
this is a test method ... ok
this is a test function ... ok
```
