### ISSUE TITLE
unexpected keyword argument 'exit'

### ISSUE THREAD

**Issue by AbeHandler** [nose-devs/nose#888]
I just tried to install and run nose from the pip package and got an error. 

    $ sudo pip install --upgrade nose 
    Requirement already up-to-date: nose in /Library/Python/2.7/site-packages  
    Cleaning up...
    $ python --version
    Python 2.7.5
    $ nosetests 
    Traceback (most recent call last):
      File "/usr/local/bin/nosetests", line 9, in <module>
       load_entry_point('nose==1.3.4', 'console_scripts', 'nosetests')()
      File "/Library/Python/2.7/site-packages/nose/core.py", line 121, in __init__
      **extra_args)
    TypeError: __init__() got an unexpected keyword argument 'exit'

**Comment by jszakmeister** [comment]
Something seems busted in your Python installation.  What does `pydoc unittest.TestProgram.__init__` say?

Mine says this:

```text
Help on method __init__ in unittest.TestProgram:

unittest.TestProgram.__init__ = __init__(self, module='__main__', defaultTest=None, argv=None, testRunner=None, testLoader=<unittest.loader.TestLoader object>, exit=True, verbosity=1, failfast=None, catchbreak=None, buffer=None) unbound unittest.main.TestProgram method
```

See the `exit=True`?  That's the keyword argument.  It sounds like your unittest.TestProgram doesn't support it and it should. :-(

It might also help to see where unittest is coming from:

```text
:: python -c 'import unittest; print repr(unittest.__file__)'
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/__init__.pyc'
```

**Comment by AbeHandler** [comment]
Yeah I think that you are correct. pydoc unittest.TestProgram.__init__ does not mention exit. How should I fix this?

    Help on method __init__ in unittest.TestProgram:

unittest.TestProgram.__init__ = __init__(self, module='__main__', defaultTest=None, argv=None, testRunner=None, testLoader=<unittest.TestLoader instance>) unbound unittest.TestProgram method

**Comment by jszakmeister** [comment]
What does `python -c 'import unittest; print repr(unittest.__file__)'` say?

**Comment by AbeHandler** [comment]
$ python -c 'import unittest; print repr(unittest.__file__)'
'/Library/Python/2.7/site-packages/unittest.pyc'

**Comment by jszakmeister** [comment]
Where did you get this version of Python from?  It's broken.  You probably need to reinstall it.  Looking Python's Mercurial repository, v2.7.5 of Python should [have the exit keyword](https://hg.python.org/cpython/file/ab05e7dd2788/Lib/unittest/main.py#l74). :-(

**Comment by jszakmeister** [comment]
BTW, don't take closing this as sign that I'm no longer willing to talk to you about it.  It's simply to mark this as "not a bug in Nose."

**Comment by AbeHandler** [comment]
No worries. Strangely, I re-installed python with brew and was still getting the error. So then I deleted two files ls /Library/Python/2.7/site-packages/unittest.py and  /Library/Python/2.7/site-packages/unittest.pyc (I was thinking this would be the first step to re-installing these modules). Once i deleted those files, it started working. I have no idea why -- but  would be curious to find out. It seems as if the bad unittest.py (or pyc) file was showing up first in the path -- blocking Python's access to a good unittest.py. Is there a way to see where python looks when it imports a module? Something akin to a which unittest.py?

**Comment by jszakmeister** [comment]
IIRC, Homebrew uses a different directory.  You may have something in your `PYTHONPATH` environment variable that's causing it to be picked up.  Either way, if was truly a 2.7 install, it should've had that parameter.  I don't know how you got those files there, but I'd be very suspicious of it all.

> Is there a way to see where python looks when it imports a module? Something akin to a which unittest.py?

Yes, that's what `python -c 'import unittest; print repr(unittest.__file__)'` does. :-)
