### ISSUE TITLE
Pypi catalog doesn't redirect to newest version

### ISSUE THREAD

**Issue by onovy** [nose-devs/nose#891]
Because this URL:
https://pypi.python.org/pypi/nose/

doesn't redirect to newest version:
https://pypi.python.org/pypi/nose/1.3.4

I can't install it using pip:
pip install -v nose
...
  Analyzing links from page https://pypi.python.org/pypi/nose/
    Skipping link http://www.python.org (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi/nose/#left-hand-navigation (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi/nose/#content-body (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=browse (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=submit_form (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=list_classifiers (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=index (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=rss (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=packages_rss (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?:action=browse&c=533&show=all (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://wiki.python.org/moin/CheeseShopTutorial (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/security (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://sourceforge.net/tracker/?group_id=66150&atid=513504 (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://bitbucket.org/pypa/pypi/issues (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://www.python.org/sigs/distutils-sig/ (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://wiki.python.org/moin/CheeseShopDev (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://www.python.org/about (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://www.python.org/news (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://www.python.org/doc (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://www.python.org/download (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://www.python.org/community (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://www.python.org/psf (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://www.python.org/dev (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi/nose (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=login (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=register_form (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=forgotten_password_form (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?:action=openid (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?:action=login&provider=Google (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi?:action=login&provider=Launchpad (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://pypi.python.org/pypi/nose/1.3.4 (from https://pypi.python.org/pypi/nose/); unknown archive format: .4
    Skipping link https://pypi.python.org/pypi/nose/1.3.3 (from https://pypi.python.org/pypi/nose/); unknown archive format: .3
    Skipping link https://pypi.python.org/pypi/nose/1.3.2 (from https://pypi.python.org/pypi/nose/); unknown archive format: .2
    Skipping link https://pypi.python.org/pypi/nose/1.3.1 (from https://pypi.python.org/pypi/nose/); unknown archive format: .1
    Skipping link https://pypi.python.org/pypi/nose/1.3.0 (from https://pypi.python.org/pypi/nose/); unknown archive format: .0
    Skipping link https://pypi.python.org/pypi/nose/1.2.1 (from https://pypi.python.org/pypi/nose/); unknown archive format: .1
    Skipping link https://pypi.python.org/pypi/nose/1.2.0 (from https://pypi.python.org/pypi/nose/); unknown archive format: .0
    Skipping link https://pypi.python.org/pypi/nose/1.1.2 (from https://pypi.python.org/pypi/nose/); unknown archive format: .2
    Skipping link https://pypi.python.org/pypi/nose/1.0.0 (from https://pypi.python.org/pypi/nose/); unknown archive format: .0
    Skipping link http://www.python.org/about/website (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link https://www.fastly.com/ (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://developer.rackspace.com/ (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://www.timparkin.co.uk/ (from https://pypi.python.org/pypi/nose/); not a file
    Skipping link http://www.python.org/about/legal (from https://pypi.python.org/pypi/nose/); not a file
  Could not find any downloads that satisfy the requirement nose

I think correct way is like this:
https://pypi.python.org/pypi/mongomock
automaticaly redirects to
https://pypi.python.org/pypi/mongomock/2.0.0

And "pip install mongomock" installs newset 2.0.0 version.

Thanks

**Comment by jszakmeister** [comment]
Isn't this a pypi problem?

**Comment by jszakmeister** [comment]
It's working for me:

```text
:: pip install -v nose
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 36096
You are using pip version 6.0.6, however version 6.0.8 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting nose
  Getting page https://pypi.python.org/simple/nose/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/nose/ HTTP/1.1" 200 655
  URLs to search for versions for nose:
  * https://pypi.python.org/simple/nose/
  Getting page https://pypi.python.org/simple/nose/
  Analyzing links from page https://pypi.python.org/simple/nose/
    Skipping link https://pypi.python.org/packages/3.1/n/nose/nose-1.0.0-py3.1.egg#md5=fc89b2f4f06fb8f4a1623d8fa3601702 (from https://pypi.python.org/simple/nose/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/py2/n/nose/nose-1.3.4-py2-none-any.whl#md5=fd999cc6fca635efa6021ebfd2c4eb4e (from https://pypi.python.org/simple/nose/), version: 1.3.4
    Skipping https://pypi.python.org/packages/py3/n/nose/nose-1.3.4-py3-none-any.whl#md5=c17bb3302bacff93a09894be4e267b1c (from https://pypi.python.org/simple/nose/) because it is not compatible with this Python
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.0.0.tar.gz#md5=47a4784c817afa6ef11a505b574584ed (from https://pypi.python.org/simple/nose/), version: 1.0.0
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.1.0.tar.gz#md5=629167a34d4f6dd4dfaa4de8ee323c93 (from https://pypi.python.org/simple/nose/), version: 1.1.0
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.1.1.tar.gz#md5=dc3025249c7abd27ac9020ec13b40db9 (from https://pypi.python.org/simple/nose/), version: 1.1.1
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.1.2.tar.gz#md5=144f237b615e23f21f6a50b2183aa817 (from https://pypi.python.org/simple/nose/), version: 1.1.2
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.2.0.tar.gz#md5=0db7fcfa8aefc5a461e90a1fc193863c (from https://pypi.python.org/simple/nose/), version: 1.2.0
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.2.1.tar.gz#md5=735e3f1ce8b07e70ee1b742a8a53585a (from https://pypi.python.org/simple/nose/), version: 1.2.1
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.3.0.tar.gz#md5=95d6d32b9d6b029c3c65674bd9e7eabe (from https://pypi.python.org/simple/nose/), version: 1.3.0
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.3.1.tar.gz#md5=672398801ddf5ba745c55c6eed79c5aa (from https://pypi.python.org/simple/nose/), version: 1.3.1
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.3.2.tar.gz#md5=00f33853c494cc7aee01b61cc4a91348 (from https://pypi.python.org/simple/nose/), version: 1.3.2
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.3.3.tar.gz#md5=42776061bf5206670cb819176dc78654 (from https://pypi.python.org/simple/nose/), version: 1.3.3
    Found link https://pypi.python.org/packages/source/n/nose/nose-1.3.4.tar.gz#md5=6ed7169887580ddc9a8e16048d38274d (from https://pypi.python.org/simple/nose/), version: 1.3.4
    Skipping https://github.com/nose-devs/nose/tarball/master#egg=nose-dev (from https://pypi.python.org/simple/nose/) because it is externally hosted.
  Using version 1.3.4 (newest of versions: 1.3.4, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.2, 1.1.1, 1.1.0, 1.0.0)
  Using cached nose-1.3.4-py2-none-any.whl
  Downloading from URL https://pypi.python.org/packages/py2/n/nose/nose-1.3.4-py2-none-any.whl#md5=fd999cc6fca635efa6021ebfd2c4eb4e (from https://pypi.python.org/simple/nose/)
Installing collected packages: nose

  changing mode of /Users/jszakmeister/.virtualenvs/stupid/bin/nosetests to 755
  changing mode of /Users/jszakmeister/.virtualenvs/stupid/bin/nosetests-2.7 to 755
Successfully installed nose-1.3.4
Cleaning up...
```

**Comment by onovy** [comment]
sorry, this is bug in my pip.conf:

extra-index-url = https://pypi.python.org/pypi/
vs.
extra-index-url = https://pypi.python.org/simple/

Second one is working fine.
