### ISSUE TITLE
python3 nosetests --with-doctest blows up

### ISSUE THREAD

**Issue by scherrey** [nose-devs/nose#899]
I'm developing a django 1.7.6 app with python 3.4.0 using nosetests 1.3.6 via django-nose 1.3 under Ubuntu 14.04.1 LTS kernel 3.16.0-31.

All my unit tests pass fine without --with-doctest but adding --with-doctest causes all kinds of strange failures even though I only have one simple doctests to see that it's getting executed.

This link shows details of my output: http://pastebin.com/bMJ9T8bN

**Comment by jszakmeister** [comment]
Unless you can narrow this down to a small, reproducible test case (that does not involve Django), then I'm not sure what I can do. :-(  It looks to me like legitimate test failures.
