### ISSUE TITLE
Ability to skip all tests but one

### ISSUE THREAD

**Issue by foxx** [nose-devs/nose#900]
In mocha, you can do the following to run only a specific test programmatically;

```
test.only(function(){});
```

Someone raised this [issue](1) on the Python mailing list and submitted example [code](2), however it doesn't appear to work now, at least with Nose.

Having such a feature would allow us to programmatically set a particular test to only be ran, for example;

```
class SomeTestCase(unittest.TestCase):
    @unittest.only()
    def test_add(self):
        """Ensure server is running"""
        return (1+2)

    def test_remove(self):
        """Ensure server is running"""
        return (1+2)
 ```

The alternative is to specify it on the command line, but this is a tedious context switch if your commands are inside a Makefile. Another alternative suggested is to modify the unittest.main() entry point, but depending on your project layout this can, again, become a tedious task.

Thoughts?

[1]: https://mail.python.org/pipermail/python-ideas/2010-August/007992.html
[2]: http://code.activestate.com/recipes/578234-unittestskip_others-decorator/

**Comment by jszakmeister** [comment]
I'm not sure what you're looking for here, but I don't see that editing code is any less of a problem than editing a Makefile.  Perhaps you can allow for some way of doing this from your Makefile instead:

```make
runtests:
    nosetests $(TESTNAME)
```

Then you can run the test with something like:

    make runtests TESTNAME=foo.bar.baz

**Comment by foxx** [comment]
It's more down to context switching between the two. For example, if you have lots of tests, you'd have to type out the entire path in the Makefile to that specific test function, e.g. `app.api.tests.sometest:SomeTestCase`. This takes considerably longer than just adding `@unittest.only` onto the method which you are currently editing. 

You are quite right that it can be added to the Makefile, but the argument is more one of convenience than anything else. Naturally this could be monkey patched in for those that want it, but it would be nice to see this functionality in the core.

Thoughts?

**Comment by jszakmeister** [comment]
I'm still not there on it.  You could simulate this feature using the attr plugin with nose.  You'd still need to allow something to be passed to the nosetests command line, but you could avoid having to change the path.

```python
from nose.plugins.attrib import attr

@attr('only')
def test_me():
    pass
```

Then on the command line select that attribute: `nosetests -a only`

**Comment by foxx** [comment]
Sadly that would still require a context switch into the Makefile to add the `-a only` as/when needed. I still prefer the approach that mocha uses, but I'll concede defeat unless anyone else pushes for this. Thank you for taking the time to reply :)
