### ISSUE TITLE
Loading tests from capitalised package name fails on Windows

### ISSUE THREAD

**Issue by takluyver** [nose-devs/nose#902]
This is a regression between 1.3.4 and 1.3.6. IPython's package is named `IPython`, with capital letters. In loading the tests, nose works with it as a path, calling `os.path.normcase()` [here](https://github.com/nose-devs/nose/blob/3510bda1e6fd7cb66fd6bb82f6c560991503fdee/nose/loader.py#L346). On Windows, that lowercases the entire path. Nose later converts the path back to a module name, which therefore starts with `ipython`, which is not importable (Python enforces case sensitivity for imports even on case-insensitive filesystems).

The resulting traceback looks like this:

```
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\29469\lib\site-packages\nose\loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\29469\lib\site-packages\nose\importer.py", line 49, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\29469\lib\site-packages\nose\importer.py", line 81, in importFromDir
    fh, filename, desc = find_module(part, path)
ImportError: No module named ipython
```

**Comment by sergiocallegari** [comment]
I confirm the issue as I also see this on my package PyDSM that contains a module called NTFdesign.
With recent versions of nose, testing with Windows is no more possible. Tests in Linux and MacOS still works as they should.

Please, treat this issue as a regression

**Comment by jszakmeister** [comment]
> On Windows, that lowercases the entire path

*sigh*  A change was made to fix #809.  Is there anything that we can do here to end up with the correct case without jumping through a thousand hoops?

> Please, treat this issue as a regression

Patches welcome.

**Comment by dcourvoi** [comment]
Another issue may that may be related to this is that on Windows, setup_package and teardown_package methods are not called at the right place when capitalized folder names are used in 1.3.6.

For example, for a folder named "Capitalized" which has an  __init.py__ (setup and teardown declared in it), this will happen when calling "nosetests.exe Capitalized":

    This is setup_package
    This is setup_package
    capitalized.testModule.test_me ... This is test me
    This is teardown_package
    capitalized.testModule2.test_me2 ... This is test me2
    capitalized.testModule3.test_me3 ... This is test me3
    This is teardown_package

If "nosetests.exe capitalized" is used, note the small 'c', then calls of setup and teardown are correct:

    This is setup_package
    capitalized.testModule.test_me ... This is test me
    capitalized.testModule2.test_me2 ... This is test me2
    capitalized.testModule3.test_me3 ... This is test me3
    This is teardown_package

**Comment by sergiocallegari** [comment]
> Patches welcome.

Can it be OK, as a start, to revert the commit that caused the regression in first place and to create a test case?  Then, a new fix for #809 can be sought without the risk of causing regressions again.

**Comment by jszakmeister** [comment]
> Can it be OK, as a start, to revert the commit that caused the regression in first place and to create a test case? Then, a new fix for #809 can be sought without the risk of causing regressions again.

I'm not keen on that idea.  It's just fixing your problem and breaking someone else again.  Besides, the real problem is who is going to help fix this?  I've not owned a copy of Windows in 13 years and don't intend to.

**Comment by takluyver** [comment]
The problem that was created - failure to load tests from a regular package with a capital letter in the name - seems clearly worse than the one that was fixed - failure to load tests from a namespace package with a capital letter in the name. So if we can't find a proper fix, I think reverting the change would make sense. I'll try to look for a proper fix, though. We can consider the logic even without testing on an actual Windows machine.

**Comment by takluyver** [comment]
#916 fixes this for me, and I don't think it should break #809.

**Comment by jszakmeister** [comment]
> The problem that was created - failure to load tests from a regular package with a capital letter in the name - seems clearly worse than the one that was fixed - failure to load tests from a namespace package with a capital letter in the name. So if we can't find a proper fix, I think reverting the change would make sense.

@takluyver I understand where you're coming from (and I appreciate your input), and it hits exactly the point: if we can't find a proper fix, we can revert.  But I want to seek a fix out first, not revert first.

> We can consider the logic even without testing on an actual Windows machine.

True, but I find that there is often something missed using that tactic. :-)

> #916 fixes this for me, and I don't think it should break #809.

Thank you!  It looks like it might do the trick, but I need to review it a little more.

**Comment by sergiocallegari** [comment]
Great to hear that this is fixed!  Thank for the work you put on this. Looking forward to a point release with the fix.

**Comment by jszakmeister** [comment]
1.3.7 has been released with this fix.
