### ISSUE TITLE
Nose time plugin (better handling when not installed)

### ISSUE THREAD

**Issue by jakirkham** [nose-devs/nose#903]
If one runs `nosetests --with-timer` and [`nose-timer`]( https://pypi.python.org/pypi/nose-timer ) is not installed, this results in an error.

    nosetests: error: no such option: --with-timer

It would be nice if it resulted in an error that is more similar to the coverage plugin. Something like this.

    nose.plugins.timer: ERROR: Timer not available: unable to import timer module

Admittedly, the interface between the two might be different, but something like this would be nice.

**Comment by jszakmeister** [comment]
It cannot.  Nose only about the options that have been registered.  In the case of the coverage plugin, it is the coverage plugin that is saying that the coverage module is not installed.  Nose has no idea who or what is implementing the unknown option, so it can't really comment on what is missing.
