### ISSUE TITLE
branch = False in .coveragerc ignored

### ISSUE THREAD

**Issue by victor-rene** [nose-devs/nose#904]
Hello,

Please refer to this ticket on BitBucket.

https://bitbucket.org/ned/coveragepy/issue/352/branch-false-in-coveragerc-ignored

Message
----
Hi, I used http://nedbatchelder.com/code/coverage/config.html to get a basic feel for how to use the configuration file. I need to support "NotImplementedError" for an abstract class. Before that I was launching nosetests and did not get branch output in the report.
After adding branch = False, I get branch output in the report which is not the expected output, and messes up my post-parsing to sort the coverage by percentage.
Not sure yet where the issue lies, it might be that nose is not compatible with this config file, but something is wrong. I run Python 2.7.9 (on Windows 7-64), coverage 3.7. Any help is appreciated. Regards.

Update
---
UPDATE: Fixed it by deleting .noseids and .coverage files. It's a caching issue. It's likely that there is no check on a change in .coveragerc to clean up the cached results.

**Comment by jszakmeister** [comment]
No, and there probably won't be such a check.  `.coveragerc` is read only by coverage itself--nose doesn't look at it at all.  What you may find helpful is the `--cover-erase` option.  If you generally run all of your tests in one fell swoop, then it's a good way to make sure that the previous coverage data is removed before running your unit tests.
