### ISSUE TITLE
Getting ImportError with simplejson on OS X 10.9.5

### ISSUE THREAD

**Issue by comatory** [nose-devs/nose#909]
Whenever I run tests on my app, I get error

`ERROR: Failure: ImportError (No module named simplejson)`

I have few tests that open my app module that contains `import simplejson`. These tests always fail. Other tests work fine. The code (importing simplejson) is not an issue, works well too. Tried creating new virtualenv and reinstalling nose and simplejson, didn't work.

I cannot replicate this issue on Fedora 21 and Ubuntu 12.0.4 (both VMs). Seems to be connected to my host OS. (OS X 10.9.5)

**Comment by kengruven** [comment]
I can't reproduce this.  Tests with `simplejson` work fine here, as long as it's using the right Python.

The first line of your `nosetests` should have a `#!`-line.  Is that the same Python that you're using, that has the `simplejson` installed?

**Comment by comatory** [comment]
@kengruven I think it's a Homebrew issue
