### ISSUE TITLE
to supress traceback with sys.tracebacklimit = 0 do not come in effect

### ISSUE THREAD

**Issue by mungayree** [nose-devs/nose#912]
I wanted to suppress the traceback output, to simple show status as ok, FAIL, ERROR
and sometime with single line to explain failure.

How do we do it ?

       import sys
       sys.tracebacklimit = 0
       def test_something():
               assert 1 == 2

        # nosetests a.py -v
        a.test_something ... FAIL

        ======================================================================
        FAIL: a.test_something
        ----------------------------------------------------------------------
        Traceback (most recent call last):
        File "/usr/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
              self.test(*self.arg)
        File "/root/a.py", line 6, in test_something
              assert 1 == 2
        AssertionError

        ----------------------------------------------------------------------
        Ran 1 test in 0.001s

        FAILED (failures=1)

**Comment by jszakmeister** [comment]
Unfortunately, you cannot--this isn't supported by Nose.
