### ISSUE TITLE
./setup.py test ignores DocTests...

### ISSUE THREAD

**Issue by jedie** [nose-devs/nose#918]
I have inserted in **setup.py** this:
```
os.environ['NOSE_DOCTEST_EXTENSION'] = 'txt'
os.environ['NOSE_WITH_DOCTEST'] = 'True'
os.environ['NOSE_WITH_DOCTESTS'] = 'True'
```

I have inserted in **.noserc** and **setup.cfg** the following:
```
[nosetests]
with-doctest=1
```

But the DocTests will be only run, if **./setup.py nosetests** will be called. Why?

**Comment by jedie** [comment]
Same as #310 ?

**Comment by montefra** [comment]
I run nosetests with doctest activated (from `setup.cfg` file) and after a recent update (now I'm on nose v1.3.7):

* in python 2.7.8: `nosetests` and `python setup.py nosetests` works
* in python 3.4.2: both of the above commands get stuck. For the latter command I get

```
['nose>=1', 'coverage', 'pyhetdex']
running nosetests
running egg_info
writing top-level names to vhc.egg-info/top_level.txt
writing dependency_links to vhc.egg-info/dependency_links.txt
writing vhc.egg-info/PKG-INFO
writing requirements to vhc.egg-info/requires.txt
writing entry points to vhc.egg-info/entry_points.txt
reading manifest file 'vhc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'vhc.egg-info/SOURCES.txt'
```

and then nothing.

I've tested with a number of older version (1.2.0, 1.3.0, 1.3.1, 1.3.6) and I get the same behaviour. The only difference is that the older version print an extra line at the end `running build_ext`

Tonight I'll test on my other computer and let you know.

**Comment by jedie** [comment]
@montefra That's a different issue, isn't it?

**Comment by montefra** [comment]
@jedie : ehm :blush: 
after rereading it, yes, you're right. I'll remove my comment and open a new issue, if there is not already one. I've also some more info now.

**Comment by jszakmeister** [comment]
There are several areas where using the built-in `test` target for distutils falls short with Nose.  This is one of them.  It's not really the fault of Nose though.  We simply cannot hook into the process to make what we need to happen, hence the [warning in the documentation](https://nose.readthedocs.org/en/latest/setuptools_integration.html).

**Comment by jedie** [comment]
Oh, i didn't see https://nose.readthedocs.org/en/latest/setuptools_integration.html :(

I have add this to my setup.py:
```
if "test" in sys.argv:
    print("\nPlease use 'nosetests' instead of 'test' to cover all tests!\n")
    print("e.g.:")
    print("     $ ./setup.py nosetests\n")
    sys.exit(-1)
```
Maybe add this to: https://nose.readthedocs.org/en/latest/setuptools_integration.html  ?!?
I created https://github.com/nose-devs/nose/issues/920 for it.
