### ISSUE TITLE
Hosted documentation does not include 1.3.7 changes

### ISSUE THREAD

**Issue by frewsxcv** [nose-devs/nose#919]
https://nose.readthedocs.org/en/latest/news.html

they are listed in this file though

https://github.com/nose-devs/nose/blob/master/CHANGELOG

**Comment by jszakmeister** [comment]
It takes a while for things to catch up.  There's some automated process that will eventually get around to it.  1.3.7 was only published this morning. :-)

**Comment by frewsxcv** [comment]
>  1.3.7 was only published this morning

Ah, was not aware of that
