### ISSUE TITLE
Tests with asyncio/aio.testing don't work

### ISSUE THREAD

**Issue by foxx** [nose-devs/nose#923]
The following example does not seem to work;

```
from unittest import TestCase
import aio.testing

class ServerTestCase(TestCase):
    @aio.testing.run_until_complete
    def test_all(self):
        return
```

However, running it with `unittest` seems to work fine, any ideas?

**Comment by jszakmeister** [comment]
Sorry, but I have no idea.

**Comment by foxx** [comment]
No worries, I'm still poking around the source code trying to figure out where it's broken, I should have an update shortly.

**Comment by foxx** [comment]
Okay, I've found the problem.

If a method is wrapped without using `functools.wraps`, then it does not inherit the original method name, which causes nose to ignore it as the method name does not begin with `test_`.

It would appear that the `aio.testing` decorators are not using `functools.wraps`, which causes the test methods to be ignored. Adding `wraps` to the decorator seems to fix the problem.

From a design perspective, decorators should typically always use `wraps()` to prevent these sorts of problems, as it's unacceptable to force developers to use introspection to handle such edge cases.

I'm going to raise an issue with `aio.testing`, and alter the name of this issue to reflect the actual problem.

**Comment by foxx** [comment]
There is one important thing to note however, why does `unittest` correctly detect the test method, where as `nose` does not? It doesn't forgive the lack of `wraps()` usage, but it might indicate a possible edge case which stops it being a drop-in replacement? @jszakmeister
