### ISSUE TITLE
Call Graph from Coverage data?

### ISSUE THREAD

**Issue by xied75** [nose-devs/nose#930]
Dear all,

new user of nose here. I was using coverage feature to see Code Coverage. Then I was wondering if the trace data can be used to generate nice looking Call Graph/Dependency Graph for packages/modules/scripts?

I tried to use pycallgraph, it doesn't work.

Best regards,

Dong

**Comment by jszakmeister** [comment]
Sorry, but I have no idea if that's possible or not.  That would be a question for for the Coverage guys than Nose.
