### ISSUE TITLE
Output is not captured if exception happened when importing test module

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [nose-devs/nose#935]
example_tests.py:
```python
print('hello, world')
assert False
```

I run `python -m nose` in the directory with this file. I get
```
F
======================================================================
FAIL: Failure: AssertionError ()
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
```

There is no
```
-------------------- >> begin captured stdout << ---------------------
hello, world
--------------------- >> end captured stdout << ----------------------
```
section like the one I would get if particular test method failed.

Observed on CPython 3.4.3 with nose 1.3.6.

**Comment by jszakmeister** [comment]
You're killing nose at the import phase and there is not test case to tie it to, so how could it report the same way as a method failing?

**Comment by Vlad-Shcherbina** [comment]
I'm not killing the test runner. As you can see, it catches the exception, and prints out traceback together with other execution details (except there is no test name, which makes perfect sense). Furthermore, it would go on with other imports and tests in other modules if I had any.

I can understand any of the two philosophies:
 - don't handle import errors at all; if an exception is thrown, let it reach `nose.run_exit`; don't capture import-time output
 - handle import errors as regular test failures (except not associated with a particular test), capture import-time output and display it together with other diagnostics

Current behavior is inconsistent.

**Comment by jszakmeister** [comment]
I didn't say you were killing the test runner, I said you're killing nose during the import phase.

> handle import errors as regular test failures (except not associated with a particular test), capture import-time output and display it together with other diagnostics

We cannot.  Capturing is a plugin to the test runner, not the loader.  It's features are not available when importing tests.

> Current behavior is inconsistent.

That's because it happens at a different phase--it cannot be "consistent".  And what use is capturing the output when you can't associate it with anything?  That seems equally inconsistent.  We capture the issue and report it later, but the capture services are not available when the problem occurs.

**Comment by Vlad-Shcherbina** [comment]
Ok, I see. I was confused by the similarity of error messages for import problems and for regular test failures (including the fact that the former ones are counted as regular test failures for statistics).

Thanks!
