### ISSUE TITLE
xunit does not capture test description

### ISSUE THREAD

**Issue by kouroshparsa** [nose-devs/nose#939]
Here is a simple test:
```
def test_example():
    "This is test description"
    pass
```
When you run `nosetests --with-xunit`
you'll get:
```
<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="1" errors="0" failures="0" skip="0"><testcase classname="test" name="test_example" time="0.001"></testcase></testsuite>
```

which is missing the test description.
This causes jenkins not show the test description.
Any ideas?

**Comment by jszakmeister** [comment]
The junit format doesn't have a field to put the description into.  Nose just doing it's own thing would break other tools that don't expect it to be there.
