### ISSUE TITLE
nosetests: error: unrecognized arguments: *

### ISSUE THREAD

**Issue by maxtheman** [nose-devs/nose#947]
I am getting the error in the title when attempting to supply arguments to nosetests on the command line.

I assumed it was an error with my tests, but that can't be because I've commented all of them out. So this is failing on an empty test suite.

Message

```
(code)Maxs-MacBook-Air: max$ nosetests -v
usage: nosetests [-h] [--auth_host_name AUTH_HOST_NAME]
                 [--noauth_local_webserver]
                 [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
                 [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
nosetests: error: unrecognized arguments: -v
```
Directory structure (if that helps):
```
home
|-module0
|-module1
|-tests
```

**Comment by jszakmeister** [comment]
Do you have code in a module that will execute if `__name__` is not `__main__`?  What version of nose are you using?  How do you build your Python module?  I've seen instances of nose picking up other files and they're not well guarded, causing them to execute, fail, and you end up with a strange error (not dissimilar to what you are seeing).

**Comment by maxtheman** [comment]
Gotcha -- no build system yet, but I do have code that will execute if `__name__` is not `__main__`.

Is there a specific way to clean that up which plays friendly with nose?

nosetests version 1.3.7 FWIW.

**Comment by Jainpriyal** [comment]
@maxtheman : I am also facing the same issue.
Please let me know how you resolved this issue:

```
[jpriyal-mba13:jsnapy/tests/unit] jpriyal% nosetests --with-coverage --cover-package=foo.bar --cover-inclusive -a unit
usage:
nosetests: error: unrecognized arguments: --with-coverage --cover-package=foo.bar --cover-inclusive -a
```

**Comment by maxtheman** [comment]
@Jainpriyal I'm not sure anymore, sorry. I think it had something to do with my import statements being structured in such a way that nose got confused, or one of my modules polluting a namespace weirdly.

**Comment by Jainpriyal** [comment]
@maxtheman : Okay, Thanks
