### ISSUE TITLE
nose ignores longMessage setting from unittest.TestCase

### ISSUE THREAD

**Issue by sobolewska** [nose-devs/nose#956]
in unittest.TestCase there is possibility to set some flags, including longMessage.
The basic usage is just to (assuming the test method is part of a class that inherits after unittest.TestCase):
```
self.longMessage = True
self.assertEqual(1, 2, "my msg")
```
but when using 
```
from nose.tools import assert_equal
self.longMessage = True
assert_equal(1, 2, 'my msg')
```
the longMessage settings are ignored, and flag is always set to False

**Comment by jszakmeister** [comment]
`assert_equal` knows nothing about your object, so it can't possibly understand the `longMessage` attribute on your instance.
