### ISSUE TITLE
'ispackage' doesn't recognize hypens as legal file/directory names 

### ISSUE THREAD

**Issue by srikanth-viswanathan** [nose-devs/nose#981]
Hyphens ('-') are valid characters in POSIX filenames. Is there a conscious reason that `ident_re` doesn't include it as part of the regex?

Code in question:
https://github.com/nose-devs/nose/blob/716d822d43db30195f795daa9fd71d54e682ec0c/nose/util.py#L17

Want to understand whether it was a conscious decision before making a pull request. Thanks!

**Comment by jszakmeister** [comment]
Hyphens are not legal in Python package names, and ident_re is used to identify packages.

**Comment by srikanth-viswanathan** [comment]
Ah, ok. I was debugging an issue where nosetests wouldn't find tests inside an application directory that had a hyphen in its name. I guess if it needs to match the rules for python packages, I'll just rename it. Thanks!
