### ISSUE TITLE
1.3.7 doesn't have option to suppress cover print

### ISSUE THREAD

**Issue by piohhmy** [nose-devs/nose#986]
In the changelog, the nose docs, and the source code there are references to suppress printing of the coverage report (e.g. --cover-no-print) for version 1.3.7.  However, downloading the latest 1.3.7 version from Pypi (or installing from pip) this option is not available.  Could it be Pypi has an old version of source associated with 1.3.7?

**Comment by jszakmeister** [comment]
No, it was an error when the PR was merged.  It should not be listed under 1.3.7.  Nose hasn't been released with that feature yet.

**Comment by thoppe** [comment]
Null update for those landing here from a search: The item is still mentioned in the docs, http://nose.readthedocs.io/en/latest/genindex.html but has not been added to nose.

**Comment by vdaskalov** [comment]
Is there any workaround for this?
